services:
  rag-knowledge-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-knowledge-bot
    env_file:
      - path: ./.env
        required: true
    restart: always
